const bins=[
{id:'BIN-0248',loc:'حي الملقا - طريق أنس',sector:'القطاع 1',state:'done',last:'09:14 ص',vehicle:'سيارة 07',lat:24.8052,lng:46.6171},
{id:'BIN-0249',loc:'حي الملقا - شارع 18',sector:'القطاع 1',state:'pending',last:'أمس 08:55 ص',vehicle:'سيارة 07',lat:24.8086,lng:46.6229},
{id:'BIN-0312',loc:'حي النرجس - طريق عثمان',sector:'القطاع 2',state:'done',last:'10:03 ص',vehicle:'سيارة 12',lat:24.8397,lng:46.6682},
{id:'BIN-0450',loc:'حي الياسمين - شارع القادسية',sector:'القطاع 2',state:'issue',last:'08:21 ص',vehicle:'سيارة 12',lat:24.8270,lng:46.6333},
{id:'BIN-0511',loc:'حي الصحافة - طريق الملك فهد',sector:'القطاع 3',state:'done',last:'07:49 ص',vehicle:'سيارة 18',lat:24.7914,lng:46.6401},
{id:'BIN-0622',loc:'حي العارض - شارع ريحانة',sector:'القطاع 3',state:'pending',last:'أمس 11:11 ص',vehicle:'سيارة 18',lat:24.8622,lng:46.6375},
{id:'BIN-0731',loc:'حي حطين - شارع السيل',sector:'القطاع 1',state:'done',last:'11:16 ص',vehicle:'سيارة 03',lat:24.7588,lng:46.6117},
{id:'BIN-0810',loc:'حي القيروان - طريق صلبوخ',sector:'القطاع 4',state:'pending',last:'أمس 09:33 ص',vehicle:'سيارة 21',lat:24.8711,lng:46.5995}
];
const vehicles=[
{name:'سيارة 07',plate:'أ ب ج 7412',worker:'أحمد محمد',state:'active',seen:'الآن',done:'56/64',pct:'87.5%'},
{name:'سيارة 12',plate:'د هـ و 2941',worker:'خالد سالم',state:'active',seen:'منذ دقيقة',done:'61/66',pct:'92.4%'},
{name:'سيارة 18',plate:'ر س ط 8840',worker:'ناصر علي',state:'active',seen:'الآن',done:'48/52',pct:'92.3%'},
{name:'سيارة 03',plate:'ك ل م 1127',worker:'سعد حسن',state:'off',seen:'منذ 18 دقيقة',done:'38/51',pct:'74.5%'},
{name:'سيارة 21',plate:'ن هـ ي 5038',worker:'فهد عمر',state:'active',seen:'منذ 3 دقائق',done:'52/58',pct:'89.7%'}
];
const workers=vehicles.map((v,i)=>({name:v.worker,id:'EMP-'+String(101+i),vehicle:v.name,state:v.state==='active'?'فعال':'غير متصل',done:v.done.split('/')[0]}));
const issues=[
{icon:'⌖',title:'BIN-0450 — مسح خارج النطاق',sub:'يبعد 87 مترًا عن الموقع المسجل · سيارة 12',badge:'تحقق GPS'},
{icon:'▱',title:'سيارة 03 غير متصلة',sub:'آخر اتصال منذ 18 دقيقة',badge:'اتصال'},
{icon:'○',title:'BIN-0622 لم تُخدم حتى الآن',sub:'القطاع 3 · آخر خدمة أمس',badge:'متبقي'},
{icon:'!',title:'3 عمليات Offline بانتظار المزامنة',sub:'سيارة 18',badge:'Offline'}
];
function stateLabel(s){return s==='done'?'<span class="state done">● تمت اليوم</span>':s==='issue'?'<span class="state issue">● تحتاج تحقق</span>':'<span class="state pending">● متبقي</span>'}
function renderBins(){let q=(document.getElementById('binSearch')?.value||'').trim();let f=document.getElementById('binFilter')?.value||'all';let rows=bins.filter(b=>(!q||(b.id+b.loc+b.sector).includes(q))&&(f==='all'||b.state===f)).map(b=>`<tr><td><b>${b.id}</b></td><td>${b.loc}</td><td>${b.sector}</td><td>${stateLabel(b.state)}</td><td>${b.last}</td><td>${b.vehicle}</td><td><button class="btn" onclick="selectQr('${b.id}')">فتح QR</button></td></tr>`).join('');document.getElementById('binsBody').innerHTML=rows;fillQrSelect()}
function renderVehicles(){document.getElementById('vehBody').innerHTML=vehicles.map(v=>`<tr><td><b>${v.name}</b></td><td>${v.plate}</td><td>${v.worker}</td><td>${v.state==='active'?'<span class="state done">● نشطة</span>':'<span class="state off">● غير متصلة</span>'}</td><td>${v.seen}</td><td>${v.done}</td><td><b>${v.pct}</b></td></tr>`).join('');document.getElementById('workerBody').innerHTML=workers.map(w=>`<tr><td><b>${w.name}</b></td><td>${w.id}</td><td>${w.vehicle}</td><td>${w.state==='فعال'?'<span class="state done">فعال</span>':'<span class="state off">غير متصل</span>'}</td><td>${w.done}</td></tr>`).join('');document.getElementById('reportBody').innerHTML=vehicles.map(v=>{let [d,t]=v.done.split('/').map(Number);return `<tr><td>${v.name}</td><td>${v.worker}</td><td>${t}</td><td>${d}</td><td>${t-d}</td><td>${v.pct}</td></tr>`}).join('')}
function renderIssues(){let html=issues.map(x=>`<div class="exception"><div class="status-icon">${x.icon}</div><div><b>${x.title}</b><span>${x.sub}</span></div><span class="badge">${x.badge}</span></div>`).join('');document.getElementById('exceptions').innerHTML=html;document.getElementById('attentionList').innerHTML=html+html}
function fillQrSelect(){let s=document.getElementById('qrBin');if(!s)return;let val=s.value||bins[0].id;s.innerHTML=bins.map(b=>`<option>${b.id}</option>`).join('');s.value=bins.some(b=>b.id===val)?val:bins[0].id;renderSticker()}
let qrLoading=null;function loadQrLib(){if(window.QRCode)return Promise.resolve();if(qrLoading)return qrLoading;qrLoading=new Promise((resolve,reject)=>{let s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return qrLoading}
function renderSticker(){let id=document.getElementById('qrBin')?.value||bins[0].id;document.getElementById('stickerBin').textContent=id;document.getElementById('stickerHint').textContent=document.getElementById('qrHint')?.value||'امسح الرمز بعد المرور على الحاوية';let box=document.getElementById('qrCanvas');if(!box)return;if(!window.QRCode){loadQrLib().then(renderSticker);return}let fresh=document.createElement('div');fresh.id='qrCanvas';box.replaceWith(fresh);new QRCode(fresh,{text:`cleantrack://service/${id}?token=CT-${btoa(id).replace(/=/g,'')}-SIG`,width:210,height:210,colorDark:'#102b31',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}
function selectQr(id){go('qr');setTimeout(()=>{document.getElementById('qrBin').value=id;renderSticker()},50)}
function renderMap(el){if(!window.maplibregl)return;let map=new maplibregl.Map({container:el,style:'https://demotiles.maplibre.org/style.json',center:[46.638,24.815],zoom:10.8,attributionControl:false});map.addControl(new maplibregl.NavigationControl(),'top-left');map.on('load',()=>{let features=[];for(let i=0;i<90;i++){let b=bins[i%bins.length];features.push({type:'Feature',geometry:{type:'Point',coordinates:[b.lng+(Math.random()-.5)*.06,b.lat+(Math.random()-.5)*.06]},properties:{state:b.state,id:b.id}})}map.addSource('bins',{type:'geojson',data:{type:'FeatureCollection',features},cluster:true,clusterMaxZoom:14,clusterRadius:44});map.addLayer({id:'clusters',type:'circle',source:'bins',filter:['has','point_count'],paint:{'circle-color':'#0e776f','circle-radius':['step',['get','point_count'],18,20,24,60,30],'circle-opacity':.88,'circle-stroke-width':3,'circle-stroke-color':'rgba(255,255,255,.9)'}});map.addLayer({id:'cluster-count',type:'symbol',source:'bins',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':12},paint:{'text-color':'#fff'}});map.addLayer({id:'points',type:'circle',source:'bins',filter:['!',['has','point_count']],paint:{'circle-radius':7,'circle-color':['match',['get','state'],'done','#16a34a','issue','#d97706','#94a3b8'],'circle-stroke-width':2,'circle-stroke-color':'#fff'}});map.on('click','clusters',e=>{let f=map.queryRenderedFeatures(e.point,{layers:['clusters']})[0];map.getSource('bins').getClusterExpansionZoom(f.properties.cluster_id,(err,z)=>{if(!err)map.easeTo({center:f.geometry.coordinates,zoom:z})})});map.on('click','points',e=>{let p=e.features[0];new maplibregl.Popup().setLngLat(p.geometry.coordinates).setHTML(`<div dir="rtl" style="font-family:Tajawal;padding:3px"><b>${p.properties.id}</b><br><span style="color:#6e7c82">${p.properties.state==='done'?'تمت اليوم':'بانتظار الخدمة'}</span></div>`).addTo(map)})});return map}
let maps={};function ensureMap(page){if(page==='dashboard'&&!maps.one)maps.one=renderMap('map');if(page==='mapPage'&&!maps.two)maps.two=renderMap('map2');setTimeout(()=>{Object.values(maps).forEach(m=>m&&m.resize())},100)}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(page).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));let meta={dashboard:['لوحة التشغيل','متابعة التنفيذ اليومي لحظيًا'],mapPage:['الخريطة المباشرة','المواقع والسيارات وحالة الخدمة'],containers:['الحاويات','إدارة نقاط الخدمة وQR'],vehicles:['السيارات','حالة الأسطول وأداء اليوم'],workers:['العمال','إدارة فرق التشغيل'],qr:['مركز QR والطباعة','توليد الملصقات باسم الشركة'],reports:['التقارير','يومي وأسبوعي وشهري'],attention:['تحتاج انتباه','الاستثناءات والمشاكل فقط'],settings:['الإعدادات','هوية الشركة وسياسات التشغيل'],driver:['تطبيق السيارة','واجهة العامل المبسطة']}[page];document.getElementById('pageTitle').textContent=meta[0];document.getElementById('pageSub').textContent=meta[1];ensureMap(page)}
document.getElementById('nav').onclick=e=>{let b=e.target.closest('button[data-page]');if(b)go(b.dataset.page)};
function openModal(id){document.getElementById(id).classList.add('show')}function closeModal(id){document.getElementById(id).classList.remove('show')}
function saveCompany(){applyCompany(document.getElementById('companyInput').value,document.getElementById('logoInput').value)}function applyCompanyModal(){applyCompany(document.getElementById('modalCompany').value,document.getElementById('modalLogo').value);closeModal('companyModal')}
function applyCompany(name,logo){name=name||'شركة النظافة';logo=logo||'ش';['sideCompany','stickerCompany','reportCompany'].forEach(id=>document.getElementById(id).textContent=name);['sideLogo','stickerLogo','reportLogo'].forEach(id=>document.getElementById(id).textContent=logo);document.getElementById('companyInput').value=name;document.getElementById('logoInput').value=logo;renderSticker()}
function addBin(){let id=document.getElementById('newBinId').value||`BIN-${1400+bins.length}`;bins.push({id,loc:'موقع جديد',sector:document.getElementById('newBinSector').value||'قطاع جديد',state:'pending',last:'—',vehicle:'غير مرتبط',lat:+document.getElementById('newLat').value,lng:+document.getElementById('newLng').value});renderBins();closeModal('addBinModal');selectQr(id)}
function simulateScan(){let d=document.getElementById('driverDone'),p=document.getElementById('driverPending'),m=document.getElementById('scanMsg');d.textContent=+d.textContent+1;p.textContent=Math.max(0,+p.textContent-1);m.innerHTML='<span style="color:#57e0ca;font-weight:700">✓ تم تسجيل BIN-0249 — الموقع مطابق</span>';setTimeout(()=>m.textContent='جاهز للمسح',2500)}
function exportCsv(){let csv='السيارة,العامل,المطلوب,المنجز,النسبة\n'+vehicles.map(v=>{let [d,t]=v.done.split('/');return `${v.name},${v.worker},${t},${d},${v.pct}`}).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='cleantrack-report.csv';a.click()}
function printReport(){let old=document.body.innerHTML;let content=document.getElementById('reportPrint').outerHTML;document.body.innerHTML=`<div dir="rtl" style="font-family:Tajawal;padding:20px">${content}</div>`;window.print();document.body.innerHTML=old;location.reload()}
function generateAllPdf(){alert('في نسخة الشركة: يتم إنشاء ملف PDF جماعي لكل الحاويات المحددة. في المعاينة استخدم طباعة الملصق الفردي لتجربة الشكل.')}
renderBins();renderVehicles();renderIssues();ensureMap('dashboard');renderSticker();