"""Simulation-engine service tests, including cross-language determinism."""
import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.models import ContributionTraits, WorldSummaryInput
from app.projection import run_scenarios
from app.rng import Mulberry32, rng_from_string, xmur3


@pytest.fixture(scope="module")
def client():
    with TestClient(app) as c:
        yield c


# --- cross-language determinism (values generated by the TS implementation) --

def test_xmur3_matches_typescript():
    assert xmur3("cross-lang-check") == 1040863944


def test_mulberry32_matches_typescript():
    rng = Mulberry32(1040863944)
    expected = [
        0.5253846433479339,
        0.16048540268093348,
        0.35351173719391227,
        0.9951580022461712,
        0.4239267511293292,
        0.3637085419613868,
    ]
    for want in expected:
        got = rng.next()
        assert abs(got - want) < 1e-15, f"{got} != {want}"


# --- scenario engine ----------------------------------------------------------

WORLD = WorldSummaryInput(
    seed="test-world",
    tick=100,
    stability=0.6,
    civilizations=8,
    mean_population=1200,
    climate=0.55,
    pollution=0.2,
    vegetation=0.45,
)

CONTRIBUTION = ContributionTraits(
    category="plant",
    traits={"growthRate": 0.4, "waterNeed": 0.6, "pollutionAbsorption": 0.8},
)


def test_scenarios_are_deterministic():
    a = run_scenarios(WORLD, CONTRIBUTION, horizon=80, runs=10)
    b = run_scenarios(WORLD, CONTRIBUTION, horizon=80, runs=10)
    assert a.model_dump() == b.model_dump()


def test_scenarios_bounds_and_order():
    report = run_scenarios(WORLD, CONTRIBUTION, horizon=100, runs=12)
    assert 0 <= report.uncertainty <= 1
    assert report.best.score >= report.most_likely.score >= report.worst.score
    assert report.runs == 12
    for outcome in [report.best, report.worst, report.most_likely]:
        for value in outcome.end_state.values():
            assert value >= 0


def test_absorbing_plant_improves_outcomes_vs_toxic_one():
    good = run_scenarios(WORLD, CONTRIBUTION, horizon=120, runs=10)
    toxic = run_scenarios(
        WORLD,
        ContributionTraits(category="plant", traits={"growthRate": 0.4, "toxicity": 0.9}),
        horizon=120,
        runs=10,
    )
    assert good.best.score >= toxic.worst.score


def test_service_endpoints(client):
    assert client.get("/health").json()["status"] == "ok"
    response = client.post("/v1/scenarios", json={
        "world": WORLD.model_dump(),
        "contribution": CONTRIBUTION.model_dump(),
        "horizon_ticks": 60,
        "runs": 8,
    })
    assert response.status_code == 200
    body = response.json()
    assert body["runs"] == 8
    assert 0 <= body["uncertainty"] <= 1


def test_service_validates_input(client):
    response = client.post("/v1/scenarios", json={"world": {"seed": "x", "stability": 5}, "runs": 2})
    assert response.status_code == 422


def test_rng_fork_independence():
    parent = rng_from_string("fork-test")
    child = parent.fork("climate")
    seq_a = [child.next() for _ in range(4)]
    child2 = parent.fork("climate")
    seq_b = [child2.next() for _ in range(4)]
    assert seq_a == seq_b
