const KEYS={ads:"e3lani_ads",saved:"e3lani_saved",posts:"e3lani_posts",profile:"e3lani_profile",notifications:"e3lani_notifications",market:"e3lani_market"};
const markets=[{code:"SA",name:"السعودية",cities:["الرياض","جدة","مكة","المدينة","الدمام","أبها","جازان","تبوك"]},{code:"AE",name:"الإمارات",cities:["دبي","أبوظبي","الشارقة","عجمان","رأس الخيمة"]},{code:"EG",name:"مصر",cities:["القاهرة","الجيزة","الإسكندرية","المنصورة","أسوان"]}];
const categories=[["السيارات","🚘"],["العقارات","🏠"],["الإلكترونيات","📱"],["الأثاث","🛋️"],["الأزياء","👕"],["الخدمات","🧰"],["الوظائف","💼"],["المعدات","🏗️"],["الحيوانات المسموح بها","🐾"],["الألعاب","🎮"],["التأجير","🔑"],["المنتجات المنزلية","🏡"],["الأسر المنتجة","🧑‍🍳"],["التذاكر","🎫"],["الصحة والجمال","💛"],["التعليم","🎓"],["السفر","✈️"],["المطاعم","🍽️"],["البراندات","◆"],["التبادل والتبرع","♻️"],["أخرى","•••"]];
const seedAds=[{id:"car",owner:"نخبة السيارات",avatar:"ن",verified:true,title:"سيارة رياضية بتفاصيل استثنائية",description:"شاهد المواصفات وتواصل مباشرة مع المعلن.",category:"السيارات",country:"SA",city:"الرياض",mediaType:"IMAGE",media:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85",contactMethod:"STORE_URL",contactValue:"",featured:true,promoted:false,views:128547,createdAt:"2026-07-31T12:00:00Z"},{id:"cafe",owner:"رِواق البن",avatar:"ر",verified:true,title:"عرض اليوم من رِواق البن",description:"تجربة قهوة بطابع عصري ومحاصيل مختارة بعناية.",category:"المطاعم",country:"SA",city:"جدة",mediaType:"IMAGE",media:"https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=85",contactMethod:"WHATSAPP",contactValue:"",featured:false,promoted:false,views:36240,createdAt:"2026-07-31T11:00:00Z"},{id:"villa",owner:"رؤية العقارية",avatar:"ر",verified:true,title:"فيلا عصرية بموقع هادئ",description:"مساحات رحبة وتصميم حديث بالقرب من أهم الخدمات.",category:"العقارات",country:"AE",city:"دبي",mediaType:"IMAGE",media:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",contactMethod:"PHONE",contactValue:"",featured:false,promoted:true,views:21874,createdAt:"2026-07-30T16:00:00Z"}];
const reportReasons=["محتوى مضلل","منتج ممنوع","احتيال","رابط ضار","انتحال","محتوى غير مناسب","إعلان مكرر","مخالفة سياسة الدولة","سبب آخر"];
let userAds=load(KEYS.ads,[]);let saved=new Set(load(KEYS.saved,[]));let posts=load(KEYS.posts,[]);
let profile=load(KEYS.profile,{name:"حسابي",bio:"صفحتك العامة للإعلانات والمنشورات المجانية.",city:"الرياض",type:"فرد",avatar:""});
let notifications=load(KEYS.notifications,[{title:"مرحبًا بك في إعلاني",text:"هذه نسخة HTML تعمل محليًا داخل AppsGeyser.",time:"الآن"}]);
let market=load(KEYS.market,"SA");let feedMode="forYou";let categoryFilter="";let pendingMedia=null;let reportAd=null;let videoObserver=null;
function load(key,fallback){try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{showToast("تعذر حفظ البيانات؛ قد تكون الصورة كبيرة")}}
function clean(value=""){return String(value).replace(/[&<>'"]/g,letter=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[letter]))}
function allAds(){return [...userAds,...seedAds]}
function getMarket(){return markets.find(item=>item.code===market)||markets[0]}
function buildTicker(){const logos=["نَخبة","URBAN","رِواق","VIA","SAND","تِقنية","رؤية","LUMA"];const group=logos.map(logo=>`<span class="ticker-logo">${logo}</span><span class="ticker-separator">إعلاني</span>`).join("");document.getElementById("tickerTrack").innerHTML=group+group}
function switchScreen(id){document.querySelectorAll(".screen").forEach(screen=>screen.classList.remove("active"));const screen=document.getElementById(id);if(screen)screen.classList.add("active");document.querySelectorAll(".nav-btn").forEach(button=>button.classList.toggle("active",button.dataset.screen===id));if(id==="saved")renderSaved();if(id==="profile")renderProfile();if(id==="notifications")renderNotifications();if(id==="categories")renderCategories()}
function selectFeed(button,mode){feedMode=mode;categoryFilter="";document.querySelectorAll(".tabs button").forEach(tab=>tab.classList.remove("active"));button.classList.add("active");renderFeed()}
function feedAds(){let ads=allAds().filter(ad=>!categoryFilter||ad.category===categoryFilter);if(feedMode==="nearby")ads=ads.filter(ad=>ad.country===market);if(feedMode==="latest")ads.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(feedMode==="forYou")ads.sort((a,b)=>{const scoreA=(a.featured?1:0)+(a.promoted?.45:0)+(a.views||0)/100000;const scoreB=(b.featured?1:0)+(b.promoted?.45:0)+(b.views||0)/100000;return scoreB-scoreA});return ads}
function renderMedia(ad){if(ad.mediaType==="VIDEO"&&ad.media)return `<video class="ad-media" src="${clean(ad.media)}" muted loop playsinline preload="metadata"></video>`;if(ad.media)return `<img class="ad-media" src="${clean(ad.media)}" alt="${clean(ad.title)}" onerror="this.style.display='none'">`;return `<div class="fallback"></div>`}
function contactText(ad){const labels={WHATSAPP:"تواصل عبر واتساب",PHONE:"اتصال بالمعلن",STORE_URL:"زيارة المتجر",PRODUCT_URL:"صفحة المنتج",EXTERNAL_URL:"فتح الرابط"};return labels[ad.contactMethod]||"تواصل مع المعلن"}
function renderFeed(){const ads=feedAds();const feed=document.getElementById("feed");if(!ads.length){feed.innerHTML=`<div style="height:100%;display:grid;place-items:center;color:#fff;text-align:center"><div><h2>لا توجد إعلانات مطابقة</h2><p>اختر قسمًا آخر أو أضف إعلانًا.</p></div></div>`;return}feed.innerHTML=ads.map(ad=>`<article class="ad" data-id="${clean(ad.id)}">${renderMedia(ad)}<div class="shade"></div><div class="badges">${ad.promoted?`<span class="badge paid">إعلان ممول</span>`:""}${ad.featured?`<span class="badge">مميز</span>`:""}</div><div class="media-label">${ad.mediaType==="VIDEO"?"فيديو":"صورة"}</div><div class="ad-content"><button class="owner" onclick="showToast('صفحة ${clean(ad.owner)}')"><span class="avatar">${clean(ad.avatar||ad.owner[0])}</span><span><strong>${clean(ad.owner)} ${ad.verified?`<span class="verify">✓</span>`:""}</strong><small>${clean(ad.city)} · ${clean(ad.category)} · ${clean(ad.country)}</small></span></button><h2 class="ad-title">${clean(ad.title)}</h2><p class="ad-description">${clean(ad.description||"")}</p><button class="cta" onclick="openContact('${clean(ad.id)}')"><span>${contactText(ad)}</span><span>←</span></button></div><div class="actions">${ad.mediaType==="VIDEO"?`<button class="action" onclick="toggleSound('${clean(ad.id)}',this)"><i>♬</i><span>الصوت</span></button>`:""}<button class="action ${saved.has(ad.id)?"saved":""}" onclick="toggleSaved('${clean(ad.id)}',this)"><i>${saved.has(ad.id)?"♥":"♡"}</i><span>حفظ</span></button><button class="action" onclick="shareAd('${clean(ad.id)}')"><i>↗</i><span>مشاركة</span></button><button class="action" onclick="openReport('${clean(ad.id)}')"><i>!</i><span>إبلاغ</span></button></div></article>`).join("");feed.scrollTop=0;setupVideos()}
function setupVideos(){if(videoObserver)videoObserver.disconnect();videoObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{const video=entry.target.querySelector("video");if(!video)return;if(entry.isIntersecting&&entry.intersectionRatio>.65)video.play().catch(()=>{});else video.pause()})},{root:document.getElementById("feed"),threshold:[.2,.65]});document.querySelectorAll(".ad").forEach(card=>videoObserver.observe(card))}
function toggleSound(id,button){const card=document.querySelector(`[data-id="${id}"]`);const video=card?.querySelector("video");if(!video)return;video.muted=!video.muted;button.querySelector("span").textContent=video.muted?"الصوت":"مسموع"}
function toggleSaved(id,button){if(saved.has(id))saved.delete(id);else saved.add(id);save(KEYS.saved,[...saved]);button.classList.toggle("saved",saved.has(id));button.querySelector("i").textContent=saved.has(id)?"♥":"♡";showToast(saved.has(id)?"تم حفظ الإعلان":"تم إلغاء الحفظ")}
function openContact(id){const ad=allAds().find(item=>item.id===id);if(!ad)return;if(!ad.contactValue){showToast("هذا إعلان للمعاينة؛ أضف إعلانك لتجربة التواصل");return}let url="";if(ad.contactMethod==="WHATSAPP")url="https://wa.me/"+ad.contactValue.replace(/\D/g,"");else if(ad.contactMethod==="PHONE")url="tel:"+ad.contactValue.replace(/[^+\d]/g,"");else url=/^https?:\/\//i.test(ad.contactValue)?ad.contactValue:"https://"+ad.contactValue;location.href=url}
async function shareAd(id){const ad=allAds().find(item=>item.id===id);if(!ad)return;const data={title:ad.title,text:`${ad.title} — ${ad.owner}`};if(navigator.share){try{await navigator.share(data);return}catch{}}try{await navigator.clipboard.writeText(data.text);showToast("تم نسخ بيانات الإعلان")}catch{showToast("المشاركة غير متاحة")}}
function renderCategories(query=""){const text=query.trim();document.getElementById("categoryGrid").innerHTML=categories.filter(category=>category[0].includes(text)).map(category=>`<button class="category" onclick="openCategory('${category[0]}')"><i>${category[1]}</i><b>${category[0]}</b></button>`).join("")}
function openCategory(category){categoryFilter=category;feedMode="latest";switchScreen("home");renderFeed();showToast("قسم "+category)}
function fillForm(){document.getElementById("adCategory").innerHTML=`<option value="">اختر القسم</option>`+categories.map(category=>`<option>${category[0]}</option>`).join("");document.getElementById("adCountry").innerHTML=markets.map(item=>`<option value="${item.code}" ${item.code===market?"selected":""}>${item.name}</option>`).join("");updateCities()}
function updateCities(){const code=document.getElementById("adCountry").value;const selected=markets.find(item=>item.code===code)||markets[0];document.getElementById("adCity").innerHTML=selected.cities.map(city=>`<option>${city}</option>`).join("")}
function updateContactPlaceholder(){const method=document.getElementById("contactMethod").value;const input=document.getElementById("contactValue");input.placeholder=method==="WHATSAPP"?"+9665XXXXXXXX":method==="PHONE"?"+966XXXXXXXXX":"https://example.com"}
async function handleMedia(event){const file=event.target.files?.[0];if(!file)return;if(file.type.startsWith("image/")&&file.size>20*1024*1024)return formError("حجم الصورة يتجاوز 20MB");if(file.type.startsWith("video/")&&file.size>200*1024*1024)return formError("حجم الفيديو يتجاوز 200MB");const box=document.getElementById("uploadBox");box.querySelectorAll("img,video").forEach(element=>element.remove());if(file.type.startsWith("image/")){const image=await compressImage(file);pendingMedia={type:"IMAGE",url:image};box.insertAdjacentHTML("afterbegin",`<img src="${image}" alt="معاينة">`)}else{const video=URL.createObjectURL(file);pendingMedia={type:"VIDEO",url:video};box.insertAdjacentHTML("afterbegin",`<video src="${video}" muted loop autoplay playsinline></video>`)}box.classList.add("has-media")}
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const max=1280;let width=image.width;let height=image.height;if(Math.max(width,height)>max){const ratio=max/Math.max(width,height);width=Math.round(width*ratio);height=Math.round(height*ratio)}const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;canvas.getContext("2d").drawImage(image,0,0,width,height);resolve(canvas.toDataURL("image/jpeg",.82))};image.src=reader.result};reader.readAsDataURL(file)})}
function formError(message){const error=document.getElementById("formError");error.textContent=message;error.classList.add("show")}
function publishAd(event){event.preventDefault();const title=document.getElementById("adTitle").value.trim();const description=document.getElementById("adDescription").value.trim();const category=document.getElementById("adCategory").value;const country=document.getElementById("adCountry").value;const city=document.getElementById("adCity").value;const contactMethod=document.getElementById("contactMethod").value;const contactValue=document.getElementById("contactValue").value.trim();if(!pendingMedia)return formError("أضف صورة أو فيديو أولًا");if(!title||!category||!country||!city||!contactValue)return formError("أكمل جميع الحقول المطلوبة");if(["STORE_URL","PRODUCT_URL","EXTERNAL_URL"].includes(contactMethod)&&!/^https?:\/\//i.test(contactValue))return formError("يجب أن يبدأ الرابط بـ https://");const ad={id:"user-"+Date.now(),owner:profile.name,avatar:profile.name[0]||"م",verified:false,title,description,category,country,city,mediaType:pendingMedia.type,media:pendingMedia.url,contactMethod,contactValue,featured:false,promoted:false,views:0,createdAt:new Date().toISOString()};userAds.unshift(ad);const storedAds=userAds.map(item=>item.mediaType==="VIDEO"&&!item.media.startsWith("data:")?{...item,media:""}:item);save(KEYS.ads,storedAds);notifications.unshift({title:"تم نشر إعلانك",text:title+" أصبح ظاهرًا في الموجز المحلي.",time:"الآن"});save(KEYS.notifications,notifications);event.target.reset();pendingMedia=null;const box=document.getElementById("uploadBox");box.classList.remove("has-media");box.querySelectorAll("img,video").forEach(element=>element.remove());fillForm();switchScreen("home");feedMode="latest";renderFeed();showToast("تم نشر الإعلان مباشرة")}
function renderSaved(){const ads=allAds().filter(ad=>saved.has(ad.id));const list=document.getElementById("savedList");if(!ads.length){list.innerHTML=`<div class="empty"><h3>لا توجد إعلانات محفوظة</h3><p>اضغط زر الحفظ داخل أي إعلان.</p></div>`;return}list.innerHTML=ads.map(ad=>listCard(ad,true)).join("")}
function listCard(ad,removeButton=false){return `<div class="list-card">${ad.media&&ad.mediaType==="IMAGE"?`<img class="list-thumb" src="${clean(ad.media)}">`:`<div class="list-thumb"></div>`}<div class="list-info"><h3>${clean(ad.title)}</h3><p>${clean(ad.city)} · ${clean(ad.category)}</p><p><b>${clean(ad.owner)}</b></p><button class="mini" onclick="focusAd('${clean(ad.id)}')">فتح</button>${removeButton?`<button class="mini" onclick="removeSaved('${clean(ad.id)}')">إزالة</button>`:""}</div></div>`}
function removeSaved(id){saved.delete(id);save(KEYS.saved,[...saved]);renderSaved()}
function focusAd(id){categoryFilter="";feedMode="latest";switchScreen("home");renderFeed();setTimeout(()=>{document.querySelector(`[data-id="${id}"]`)?.scrollIntoView({behavior:"smooth"})},100)}
function renderProfile(){document.getElementById("profileName").textContent=profile.name;document.getElementById("profileBio").textContent=profile.bio+" · "+profile.city+" · "+profile.type;const avatar=document.getElementById("profileAvatar");avatar.innerHTML=profile.avatar?`<img src="${clean(profile.avatar)}">`:clean(profile.name[0]||"م");document.getElementById("myAdsCount").textContent=userAds.length;document.getElementById("myPostsCount").textContent=posts.length;document.getElementById("myViews").textContent=userAds.reduce((total,ad)=>total+(ad.views||0),0);profileTab(document.querySelector(".profile-tabs button"),"ads")}
function profileTab(button,type){document.querySelectorAll(".profile-tabs button").forEach(tab=>tab.classList.toggle("active",tab===button));const content=document.getElementById("profileContent");if(type==="ads"){if(!userAds.length){content.innerHTML=`<div class="empty"><h3>لا توجد إعلانات لك</h3><p>استخدم زر «أضف إعلانًا» للنشر.</p></div>`;return}content.innerHTML=`<div class="media-grid">${userAds.map(ad=>`<button class="media-item" onclick="focusAd('${clean(ad.id)}')">${ad.media&&ad.mediaType==="IMAGE"?`<img src="${clean(ad.media)}">`:`<div class="fallback"></div>`}<span>${clean(ad.title)}</span></button>`).join("")}</div>`}else{content.innerHTML=`<button class="primary" style="margin-bottom:12px" onclick="openSheet('postSheet')">إضافة منشور مجاني</button>${posts.length?`<div class="media-grid">${posts.map(post=>`<button class="media-item">${post.media?`<img src="${clean(post.media)}">`:`<div class="fallback"></div>`}<span>${clean(post.title)}</span></button>`).join("")}</div>`:`<div class="empty"><h3>لا توجد منشورات</h3><p>المنشورات تظهر داخل صفحتك فقط.</p></div>`}`}}
async function changeAvatar(event){const file=event.target.files?.[0];if(!file)return;profile.avatar=await compressImage(file);save(KEYS.profile,profile);renderProfile()}
function openProfile(){document.getElementById("editName").value=profile.name;document.getElementById("editBio").value=profile.bio;document.getElementById("editCity").value=profile.city;document.getElementById("editType").value=profile.type;openSheet("profileSheet")}
function saveProfile(event){event.preventDefault();profile={...profile,name:document.getElementById("editName").value.trim()||"حسابي",bio:document.getElementById("editBio").value.trim()||"صفحة عامة على إعلاني",city:document.getElementById("editCity").value.trim()||"الرياض",type:document.getElementById("editType").value};save(KEYS.profile,profile);closeSheet("profileSheet");renderProfile();showToast("تم حفظ الحساب")}
async function createPost(event){event.preventDefault();const file=document.getElementById("postMedia").files?.[0];const media=file?await compressImage(file):"";posts.unshift({id:"post-"+Date.now(),title:document.getElementById("postTitle").value.trim(),text:document.getElementById("postText").value.trim(),media,createdAt:new Date().toISOString()});save(KEYS.posts,posts);event.target.reset();closeSheet("postSheet");renderProfile();const postsTab=document.querySelectorAll(".profile-tabs button")[1];profileTab(postsTab,"posts");showToast("تم نشر المنشور داخل صفحتك فقط")}
async function shareProfile(){const data={title:profile.name,text:"صفحة "+profile.name+" على إعلاني"};if(navigator.share){try{await navigator.share(data);return}catch{}}showToast("تم تجهيز مشاركة الصفحة")}
function openSearch(){switchScreen("searchScreen");renderSearch();setTimeout(()=>document.getElementById("globalSearch").focus(),100)}
function renderSearch(){const query=(document.getElementById("globalSearch").value||"").trim().toLowerCase();const results=allAds().filter(ad=>{const text=[ad.title,ad.description,ad.owner,ad.category,ad.city].join(" ").toLowerCase();return !query||text.includes(query)});document.getElementById("searchResults").innerHTML=results.length?results.map(ad=>listCard(ad)).join(""):`<div class="empty"><h3>لا توجد نتائج مطابقة</h3></div>`}
function renderNotifications(){document.getElementById("notificationsList").innerHTML=notifications.length?notifications.map(notification=>`<div class="list-card"><div class="list-info"><h3>${clean(notification.title)}</h3><p>${clean(notification.text)}</p><p>${clean(notification.time)}</p></div></div>`).join(""):`<div class="empty"><h3>لا توجد إشعارات</h3></div>`}
function openMarket(){document.getElementById("marketOptions").innerHTML=markets.map(item=>`<button class="option" onclick="selectMarket('${item.code}')"><span class="market-code">${item.code}</span><b>${item.name}</b></button>`).join("");openSheet("marketSheet")}
function selectMarket(code){market=code;save(KEYS.market,market);const selected=getMarket();document.getElementById("marketName").textContent=selected.name;document.getElementById("marketCode").textContent=selected.code;fillForm();closeSheet("marketSheet");renderFeed();showToast("تم اختيار سوق "+selected.name)}
function openReport(id){reportAd=id;document.getElementById("reportOptions").innerHTML=reportReasons.map((reason,index)=>`<label class="option"><input type="radio" name="reportReason" value="${clean(reason)}" ${index===0?"checked":""}><span>${clean(reason)}</span></label>`).join("");openSheet("reportSheet")}
function submitReport(){const reason=document.querySelector('input[name="reportReason"]:checked')?.value;if(!reason)return;notifications.unshift({title:"تم استلام البلاغ",text:"سبب البلاغ: "+reason,time:"الآن"});save(KEYS.notifications,notifications);closeSheet("reportSheet");showToast("تم تسجيل البلاغ")}
function openSheet(id){document.getElementById(id).classList.add("open")}
function closeSheet(id){document.getElementById(id).classList.remove("open")}
function closeBackdrop(event,id){if(event.target.id===id)closeSheet(id)}
let toastTimer;function showToast(message){const toast=document.getElementById("toast");toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),1800)}
function init(){buildTicker();renderCategories();fillForm();const selected=getMarket();document.getElementById("marketName").textContent=selected.name;document.getElementById("marketCode").textContent=selected.code;renderFeed();renderSaved();renderProfile();renderNotifications()}
init();
