import { ScrollView, StyleSheet, Text, View } from "react-native";
import { AdminShell } from "@/components/e3lani/admin-shell";
import { EmptyState, StatusBadge } from "@/components/e3lani/ui";
import { BRAND } from "@/lib/e3lani-data";
import { useE3lani } from "@/lib/e3lani-store";
import { useI18n } from "@/lib/i18n";

export default function Payments() {
  const store = useE3lani(); const { locale } = useI18n();
  return <AdminShell title={locale === "ar" ? "المدفوعات والفواتير" : "Payments & invoices"}><ScrollView contentContainerStyle={s.page}><View style={s.banner}><Text style={s.bannerTitle}>{locale === "ar" ? "بيئة الدفع الحالية: Sandbox" : "Current payment environment: Sandbox"}</Text><Text style={s.bannerText}>{locale === "ar" ? "لا توجد حركة مالية فعلية، وتظهر العمليات التجريبية فقط." : "No real money is moved; only test transactions are shown."}</Text></View>{store.orders.length ? store.orders.map((order) => <View key={order.id} style={s.card}><View style={s.row}><StatusBadge status={order.status === "paid" ? "active" : "awaiting_payment"} /><Text style={s.id}>{order.id}</Text></View><Text style={s.amount}>{(order.totalHalalas / 100).toFixed(2)} SAR</Text><Text style={s.meta}>{order.adId} • {order.provider} • {new Date(order.createdAt).toLocaleDateString()}</Text><Text style={s.invoice}>{locale === "ar" ? "الفاتورة" : "Invoice"}: {store.invoices.find((invoice) => invoice.orderId === order.id)?.number ?? "—"}</Text></View>) : <EmptyState icon="payments" title={locale === "ar" ? "لا توجد عمليات دفع" : "No payments yet"} text={locale === "ar" ? "ستظهر الطلبات المؤكدة والتجريبية هنا." : "Confirmed and sandbox orders will appear here."} />}</ScrollView></AdminShell>;
}
const s = StyleSheet.create({ page: { padding: 16, paddingBottom: 35, gap: 10 }, banner: { padding: 16, borderRadius: 19, backgroundColor: BRAND.warning }, bannerTitle: { color: BRAND.white, fontSize: 15, lineHeight: 21, fontWeight: "900", textAlign: "right" }, bannerText: { marginTop: 4, color: BRAND.white, fontSize: 11, lineHeight: 18, textAlign: "right" }, card: { borderWidth: 1, borderColor: BRAND.border, borderRadius: 20, padding: 16, backgroundColor: BRAND.white }, row: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, id: { color: BRAND.muted, fontSize: 11 }, amount: { marginTop: 10, color: BRAND.black, fontSize: 23, lineHeight: 31, fontWeight: "900", textAlign: "right" }, meta: { marginTop: 3, color: BRAND.muted, fontSize: 11, textAlign: "right" }, invoice: { marginTop: 8, color: BRAND.black, fontSize: 13, fontWeight: "800", textAlign: "right" } });
