import type { ContributionCategory, StructuredContribution } from "@planet/shared-types";
import { balanceContribution, suggestBiomesFromText } from "@planet/simulation-models";
import { detectInjection, sanitizeUserText } from "@planet/validation";

export interface ProviderResult {
  structured: StructuredContribution;
  provider: string;
  sandbox: boolean;
  raw?: unknown;
}

export interface NarrateResult {
  narrative: string;
  narrativeAr: string;
  provider: string;
  sandbox: boolean;
}

export interface AiProvider {
  name: string;
  analyze(category: ContributionCategory, idea: string, locale: string): Promise<ProviderResult>;
  narrate(
    events: Array<{ title: string; titleAr: string; description: string; descriptionAr: string; type: string }>,
    locale: string,
  ): Promise<NarrateResult>;
}

function clamp01(n: number) {
  return Math.max(0, Math.min(1, n));
}

export class SandboxProvider implements AiProvider {
  name = "sandbox";

  async analyze(category: ContributionCategory, idea: string, locale: string): Promise<ProviderResult> {
    const text = sanitizeUserText(idea);
    if (detectInjection(text)) {
      throw new Error("INJECTION");
    }
    const biomes = suggestBiomesFromText(text);
    const traits: Record<string, number> = {
      size: /عملاق|giant/i.test(text) ? 0.85 : 0.4,
      growthRate: /سريع|fast|ينمو/i.test(text) ? 0.5 : 0.3,
      waterNeed: /ماء|water/i.test(text) ? 0.75 : 0.45,
      pollutionAbsorption: /تلوث|pollution/i.test(text) ? 0.9 : 0.1,
      nightLuminosity: /يضيء|light|ليل/i.test(text) ? 0.8 : 0.05,
      energyOutput: /طاقة|energy|شمس/i.test(text) ? 0.7 : 0.05,
      coldResistance: /برد|cold/i.test(text) ? 0.7 : 0.35,
      heatResistance: /حر|heat/i.test(text) ? 0.7 : 0.4,
      aggression: /عدوان|مفترس/i.test(text) ? 0.65 : 0.2,
      intelligence: /ذكي|علم/i.test(text) ? 0.65 : 0.3,
      economicValue: /تجارة|ثروة/i.test(text) ? 0.65 : 0.3,
      contagiousness: category === "disease" ? 0.45 : 0,
      lethality: category === "disease" ? 0.25 : 0,
      adaptability: 0.5,
      fertilityBoost: category === "plant" ? 0.2 : 0,
    };

    const risks: string[] = [];
    if ((traits.waterNeed ?? 0) > 0.65) risks.push("high_water_consumption");
    if ((traits.growthRate ?? 0) > 0.45) risks.push("ecosystem_competition");
    if ((traits.energyOutput ?? 0) > 0.5) risks.push("resource_conflict");

    const benefits: string[] = [];
    if ((traits.pollutionAbsorption ?? 0) > 0.4) benefits.push("pollution_reduction");
    if ((traits.energyOutput ?? 0) > 0.3) benefits.push("energy_potential");

    const nameAr = text.slice(0, 40) || "عنصر جديد";
    const structured = balanceContribution({
      category,
      name: locale === "en" ? text.slice(0, 40) || "New Element" : `Element: ${nameAr}`,
      nameAr,
      description: `Sandbox structured output from user idea.`,
      descriptionAr: `مخرجات منظمة من صندوق الرمل لفكرة المستخدم.`,
      traits,
      possibleBiomes: biomes,
      risks,
      benefits,
      balanceNotes: ["Generated by SandboxProvider — not a live LLM"],
      wasBalanced: false,
      originalIdea: text,
    });

    return { structured, provider: this.name, sandbox: true };
  }

  async narrate(events: NarrateResult extends never ? never : Array<{ description: string; descriptionAr: string }>): Promise<NarrateResult> {
    // Only narrate from provided events — never invent
    const narrative = events.map((e) => e.description).join(" ");
    const narrativeAr = events.map((e) => e.descriptionAr).join(" ");
    return {
      narrative: narrative || "No simulation events to narrate.",
      narrativeAr: narrativeAr || "لا توجد أحداث محاكاة لصياغتها.",
      provider: this.name,
      sandbox: true,
    };
  }
}

/** OpenAI adapter — inactive without key; clearly sandboxed fallback */
export class OpenAIProvider implements AiProvider {
  name = "openai";
  constructor(private apiKey: string) {}

  async analyze(category: ContributionCategory, idea: string, locale: string): Promise<ProviderResult> {
    if (!this.apiKey) return new SandboxProvider().analyze(category, idea, locale);
    // Structured call placeholder — uses Responses/Chat JSON schema in production
    // For safety in this environment we do not call external APIs unless key present AND fetch succeeds
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content:
                "Convert user world-element ideas into JSON: category,name,nameAr,description,descriptionAr,traits(object of 0-1 floats),possibleBiomes[],risks[],benefits[]. No overpowered traits.",
            },
            { role: "user", content: `category=${category}; locale=${locale}; idea=${idea}` },
          ],
        }),
        signal: AbortSignal.timeout(12000),
      });
      if (!res.ok) return new SandboxProvider().analyze(category, idea, locale);
      const data = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
      const content = data.choices?.[0]?.message?.content;
      if (!content) return new SandboxProvider().analyze(category, idea, locale);
      const parsed = JSON.parse(content) as Partial<StructuredContribution>;
      const structured = balanceContribution({
        category,
        name: parsed.name ?? "Element",
        nameAr: parsed.nameAr ?? "عنصر",
        description: parsed.description ?? idea,
        descriptionAr: parsed.descriptionAr ?? idea,
        traits: Object.fromEntries(
          Object.entries(parsed.traits ?? {}).map(([k, v]) => [k, clamp01(Number(v))]),
        ),
        possibleBiomes: parsed.possibleBiomes ?? suggestBiomesFromText(idea),
        risks: parsed.risks ?? [],
        benefits: parsed.benefits ?? [],
        balanceNotes: [],
        wasBalanced: false,
        originalIdea: idea,
      });
      return { structured, provider: this.name, sandbox: false, raw: parsed };
    } catch {
      return new SandboxProvider().analyze(category, idea, locale);
    }
  }

  async narrate(
    events: Array<{ title: string; titleAr: string; description: string; descriptionAr: string; type: string }>,
    locale: string,
  ): Promise<NarrateResult> {
    if (!this.apiKey) return new SandboxProvider().narrate(events);
    // Grounding rule: only rephrase given events
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            {
              role: "system",
              content:
                "Write a short bilingual narrative using ONLY the provided simulation events. Never invent facts. Return JSON {narrative, narrativeAr}.",
            },
            { role: "user", content: JSON.stringify({ locale, events }) },
          ],
          response_format: { type: "json_object" },
        }),
        signal: AbortSignal.timeout(12000),
      });
      if (!res.ok) return new SandboxProvider().narrate(events);
      const data = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
      const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}") as {
        narrative?: string;
        narrativeAr?: string;
      };
      return {
        narrative: parsed.narrative ?? events.map((e) => e.description).join(" "),
        narrativeAr: parsed.narrativeAr ?? events.map((e) => e.descriptionAr).join(" "),
        provider: this.name,
        sandbox: false,
      };
    } catch {
      return new SandboxProvider().narrate(events);
    }
  }
}

export class AnthropicProvider extends SandboxProvider {
  name = "anthropic";
  constructor(private apiKey: string) {
    super();
  }
  override async analyze(category: ContributionCategory, idea: string, locale: string) {
    if (!this.apiKey) return super.analyze(category, idea, locale);
    // Adapter ready — falls back until key + network allowed
    return super.analyze(category, idea, locale);
  }
}

export class GeminiProvider extends SandboxProvider {
  name = "gemini";
  constructor(private apiKey: string) {
    super();
  }
}

export function createProvider(): AiProvider {
  const which = (process.env.AI_PROVIDER ?? "sandbox").toLowerCase();
  if (which === "openai" && process.env.OPENAI_API_KEY) {
    return new OpenAIProvider(process.env.OPENAI_API_KEY);
  }
  if (which === "anthropic" && process.env.ANTHROPIC_API_KEY) {
    return new AnthropicProvider(process.env.ANTHROPIC_API_KEY);
  }
  if (which === "gemini" && process.env.GEMINI_API_KEY) {
    return new GeminiProvider(process.env.GEMINI_API_KEY);
  }
  return new SandboxProvider();
}
